site_name: My Project
site_url: https://github.com/Wordcab/wordcab-transcribe
site_author: Author
site_description: Site description.

repo_name: Wordcab/wordcab-transcribe
repo_url: https://github.com/Wordcab/wordcab-transcribe

copyright: Copyright (c) 2023-present Wordcab <info@wordcab.com>

theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: amber
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: amber
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  icon:
    logo: material/microphone-message
  features:
    - content.tabs.link

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.tasklist:
      custom_checkbox: true

plugins:
  - search:
  - git-revision-date-localized:
      type: timeago
      enable_creation_date: true
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: google
            show_root_full_path: false
            show_root_heading: false
            show_root_toc_entry: false
            show_symbol_type_toc: true

extra:
  social:
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/wordcab
    - icon: fontawesome/brands/github
      link: https://github.com/Wordcab
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/wordcab

nav:
  - 👋 Getting Started: index.md
  - 📖 Usage:
    - ENV variables: usage/env.md
    - Launch: usage/launch.md
  - 📚 Reference:
    - Config: reference/config.md
    - Services: reference/services.md
    - Schemas: reference/schemas.md
  - 🚀 Contributing: contributing.md
  - 📝 License: license.md
