name: Quality Checks

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
    paths:
      - .github/workflows/ci-cd.yaml
      - src/**
      - tests/**
  release:
    types:
      - published

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  check-quality:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: setup-python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - name: install-dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ".[quality]"

      - name: check-quality
        run: |
          black --check --diff --preview src tests
          ruff src tests

  run-tests:
    needs: check-quality

    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: setup-python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: install-dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ".[tests]"

      - name: run-tests
        run: pytest --cov=wordcab_transcribe --cov-report=term-missing tests/ -s --durations 0

  deploy-docs:
    needs: run-tests
    if: (github.event_name == 'release') || (github.event_name == 'push' && github.ref == 'refs/heads/main')

    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: setup-python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: install-dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e ".[docs]"

      - name: deploy-to-gh-pages
        run: mkdocs gh-deploy --force
